### ISSUE TITLE
code does not work

### ISSUE THREAD

**Issue by Euwakwe** [AlexWiles/pai#1]
(base) manny@Emmanuels-MacBook-Pro-2 ~ % pai
Traceback (most recent call last):
  File "/Users/manny/opt/anaconda3/bin/pai", line 5, in <module>
    from pai.cli import main
  File "/Users/manny/opt/anaconda3/lib/python3.9/site-packages/pai/cli.py", line 5, in <module>
    from pai.console import Console
  File "/Users/manny/opt/anaconda3/lib/python3.9/site-packages/pai/console.py", line 5, in <module>
    from pai.history import HistoryNode, HistoryTree
  File "/Users/manny/opt/anaconda3/lib/python3.9/site-packages/pai/history.py", line 5, in <module>
    class HistoryNode:
  File "/Users/manny/opt/anaconda3/lib/python3.9/site-packages/pai/history.py", line 34, in HistoryNode
    Data = UserCode | LLMCode | LLMMessage | LLMError | Root
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by AlexWiles** [comment]
Thanks for the report!

It was a Python version compatibility issue. 
I've pushed a fix and released a new version (0.1.14) that supports Python 3.8+
